version: '3'

services:
  pet-adoption:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Persist database and uploaded images
      - ./pets.db:/app/backend/pets.db
      - ./public/images:/app/public/images
    environment:
      - PORT=5000
      # Use the values from .env file
      - REACT_APP_ADMIN_PASSWORD=${REACT_APP_ADMIN_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped